"""Output field inventory for LLM Judge output schema."""

from __future__ import annotations

REQUIRED_OUTPUT_SECTIONS = (
    "competitive_classification",
    "competitive_evaluation",
    "supporting_evidence",
    "static_analysis_result",
    "decision_pattern_analysis",
    "confidence_assessment",
    "final_summary",
)

CANONICAL_OUTPUT_FIELDS = (
    "competitive_classification.classification",
    "competitive_classification.score",
    "competitive_classification.confidence",
    "competitive_classification.metadata",
    "competitive_evaluation.summary",
    "competitive_evaluation.immediate_effects",
    "competitive_evaluation.long_term_effects",
    "competitive_evaluation.affected_players",
    "competitive_evaluation.key_findings",
    "competitive_evaluation.metadata",
    "supporting_evidence.board_state_evidence",
    "supporting_evidence.trade_information_evidence",
    "supporting_evidence.game_configuration_evidence",
    "supporting_evidence.static_algorithm_evidence",
    "supporting_evidence.metadata",
    "static_analysis_result.requested_mode",
    "static_analysis_result.execution_mode",
    "static_analysis_result.evidence_source",
    "static_analysis_result.algorithm_id",
    "static_analysis_result.algorithm_version",
    "static_analysis_result.dependency_versions",
    "static_analysis_result.execution_status",
    "static_analysis_result.fallback_attempted",
    "static_analysis_result.fallback_reason",
    "static_analysis_result.competitive_evaluation_used_static_evidence",
    "static_analysis_result.generated_static_algorithm_evidence",
    "static_analysis_result.limitations",
    "static_analysis_result.errors",
    "static_analysis_result.metadata",
    "decision_pattern_analysis.matched_patterns",
    "decision_pattern_analysis.unmatched_patterns",
    "decision_pattern_analysis.summary",
    "decision_pattern_analysis.metadata",
    "confidence_assessment.overall_confidence",
    "confidence_assessment.confidence_factors",
    "confidence_assessment.limitations",
    "confidence_assessment.metadata",
    "final_summary.summary",
    "final_summary.highlights",
    "final_summary.metadata",
)
