"""Structured output-field coverage registry.

Maps every canonical output field to its focused unit test, scenario, and expected invariant.
Consumed by field-level unit tests and the output coverage guard.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class OutputFieldCoverageEntry:
    """Coverage mapping for one canonical output field."""

    field_key: str
    output_path: str
    meaning: str
    calculation_type: str
    scenario_function: str
    scenario_json: str
    test_module: str
    test_name: str
    expected_invariant: str
    assertion_tier: str = "STRUCTURAL"
    waived: bool = False
    waiver_reason: str = ""


OUTPUT_FIELD_COVERAGE: tuple[OutputFieldCoverageEntry, ...] = (
    OutputFieldCoverageEntry(
        field_key="algorithm_id",
        output_path="algorithm_id",
        meaning="Machine-readable algorithm identifier (must equal specification_id)",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_algorithm_id",
        expected_invariant="monopoly_static_algorithm",
    ),
    OutputFieldCoverageEntry(
        field_key="algorithm_name",
        output_path="algorithm_name",
        meaning="Human-readable algorithm name",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_algorithm_name",
        expected_invariant="Static Trade Imbalance Evaluator",
    ),
    OutputFieldCoverageEntry(
        field_key="algorithm_version",
        output_path="algorithm_version",
        meaning="Implemented specification_version",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_algorithm_version",
        expected_invariant="1.0",
    ),
    OutputFieldCoverageEntry(
        field_key="available_construction_budget.cash",
        output_path="intermediate_values.cash",
        meaning="Cash component of construction budget",
        calculation_type="available_construction_budget",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_available_construction_budget_fields",
        test_name="test_available_construction_budget_cash",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="available_risk_resources.mortgage_capacity",
        output_path="intermediate_values.mortgage_capacity",
        meaning="Mortgage capacity component of risk resources",
        calculation_type="available_risk_resources",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_risk_resource_fields",
        test_name="test_available_risk_resources_mortgage_capacity",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.building_value",
        output_path="intermediate_values.building_value",
        meaning="Total building liquidation value",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_building_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.card_value",
        output_path="intermediate_values.card_value",
        meaning="Total card value",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_card_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.cash_received",
        output_path="intermediate_values.cash_received",
        meaning="Cash received by player",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_cash_received",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_item.building_value",
        output_path="intermediate_values.line_items[*].building_value",
        meaning="Building liquidation value for property",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_item_building_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_item.printed_value",
        output_path="intermediate_values.line_items[*].printed_value",
        meaning="Property printed value",
        calculation_type="base_asset_value",
        scenario_function="mortgagedPropertyTransferInput",
        scenario_json="base_asset_value/mortgaged_property_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_item_printed_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_item.property_id",
        output_path="intermediate_values.line_items[*].property_id",
        meaning="Property identifier",
        calculation_type="base_asset_value",
        scenario_function="mortgagedPropertyTransferInput",
        scenario_json="base_asset_value/mortgaged_property_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_item_property_id",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_item.transfer_id",
        output_path="intermediate_values.line_items[*].transfer_id",
        meaning="Transfer identifier",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_item_transfer_id",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_item.type",
        output_path="intermediate_values.line_items[*].type",
        meaning="Line item type",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_item_type",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.line_items",
        output_path="intermediate_values.line_items",
        meaning="Per-transfer line items",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_line_items",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="base_asset_value.property_value",
        output_path="intermediate_values.property_value",
        meaning="Total property value received",
        calculation_type="base_asset_value",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_base_asset_value_fields",
        test_name="test_base_asset_value_property_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="blocking_value.per_property",
        output_path="intermediate_values.per_property",
        meaning="Per-property blocking value breakdown",
        calculation_type="blocking_value",
        scenario_function="strategicBlockingTradeInput",
        scenario_json="blocking_value/strategic_blocking_trade.json",
        test_module="test_blocking_value_fields",
        test_name="test_blocking_value_per_property",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.apparent_overpayer",
        output_path="intermediate_values.apparent_overpayer",
        meaning="Player with lower strategic value",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_apparent_overpayer",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.automatic_rule.flag_generated",
        output_path="intermediate_values.automatic_rules[*].flag_generated",
        meaning="Flag generated (if any)",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_automatic_rule_flag_generated",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.automatic_rule.predicate_result",
        output_path="intermediate_values.automatic_rules[*].predicate_result",
        meaning="Whether rule predicate matched",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_automatic_rule_predicate_result",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.automatic_rule.rule",
        output_path="intermediate_values.automatic_rules[*].rule",
        meaning="Rule identifier",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_automatic_rule_rule",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.automatic_rules",
        output_path="intermediate_values.automatic_rules",
        meaning="Automatic flag rule evaluations",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_automatic_rules",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.final_classification",
        output_path="intermediate_values.final_classification",
        meaning="Final classification value",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_final_classification",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.flags_after_initiator_adjustment",
        output_path="intermediate_values.flags_after_initiator_adjustment",
        meaning="Flags after initiator adjustment",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_flags_after_initiator_adjustment",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.flags_before_initiator_adjustment",
        output_path="intermediate_values.flags_before_initiator_adjustment",
        meaning="Flags before initiator adjustment",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_flags_before_initiator_adjustment",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.initiating_player_id",
        output_path="intermediate_values.initiating_player_id",
        meaning="Trade initiator player ID",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_initiating_player_id",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.initiator_adjustment_applied",
        output_path="intermediate_values.initiator_adjustment_applied",
        meaning="Whether adjustment was applied",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_initiator_adjustment_applied",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.initiator_rule_evaluated",
        output_path="intermediate_values.initiator_rule_evaluated",
        meaning="Whether initiator adjustment was evaluated",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_initiator_rule_evaluated",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.strong_flag_count",
        output_path="intermediate_values.strong_flag_count",
        meaning="Count of strong flags",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_strong_flag_count",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.strong_flags",
        output_path="intermediate_values.strong_flags",
        meaning="Strong flags present",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_strong_flags",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="classification.trade_ratio",
        output_path="intermediate_values.trade_ratio",
        meaning="Trade ratio used for classification",
        calculation_type="final_static_classification",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_static_classification_fields",
        test_name="test_classification_trade_ratio",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.classification",
        output_path="final_conclusions.classification",
        meaning="Final static classification",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_classification",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.classification_calculation_id",
        output_path="final_conclusions.classification_calculation_id",
        meaning="Supporting classification calculation ID",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_classification_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.flags",
        output_path="final_conclusions.flags",
        meaning="Generated flags",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_flags",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.flags.calculation_id",
        output_path="final_conclusions.flags.calculation_id",
        meaning="Supporting calculation ID",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_flags_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.flags.values",
        output_path="final_conclusions.flags.values",
        meaning="Flag values array",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_flags_values",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_labels",
        output_path="final_conclusions.risk_labels",
        meaning="Risk labels per player",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_labels",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_labels.player.after",
        output_path="final_conclusions.risk_labels[player].after",
        meaning="After-trade risk label",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_labels_player_after",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_labels.player.after_calculation_id",
        output_path="final_conclusions.risk_labels[player].after_calculation_id",
        meaning="Supporting after calculation ID",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_labels_player_after_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_labels.player.before",
        output_path="final_conclusions.risk_labels[player].before",
        meaning="Before-trade risk label",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_labels_player_before",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_labels.player.before_calculation_id",
        output_path="final_conclusions.risk_labels[player].before_calculation_id",
        meaning="Supporting before calculation ID",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_labels_player_before_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_warnings",
        output_path="final_conclusions.risk_warnings",
        meaning="Risk warnings",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_warnings",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_warnings.calculation_ids",
        output_path="final_conclusions.risk_warnings.calculation_ids",
        meaning="Supporting calculation IDs",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_warnings_calculation_ids",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.risk_warnings.values",
        output_path="final_conclusions.risk_warnings.values",
        meaning="Warning values array",
        calculation_type="-",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_risk_warnings_values",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.strategic_value",
        output_path="final_conclusions.strategic_value",
        meaning="Strategic value per player",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_strategic_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.strategic_value.player.calculation_id",
        output_path="final_conclusions.strategic_value[player].calculation_id",
        meaning="Supporting calculation ID",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_strategic_value_player_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.strategic_value.player.value",
        output_path="final_conclusions.strategic_value[player].value",
        meaning="Player's strategic value",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_strategic_value_player_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.trade_ratio",
        output_path="final_conclusions.trade_ratio",
        meaning="Trade ratio conclusion",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_trade_ratio",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.trade_ratio.calculation_id",
        output_path="final_conclusions.trade_ratio.calculation_id",
        meaning="Supporting calculation ID",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_trade_ratio_calculation_id",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="conclusions.trade_ratio.value",
        output_path="final_conclusions.trade_ratio.value",
        meaning="Published trade ratio value",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_final_conclusion_fields",
        test_name="test_conclusions_trade_ratio_value",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="coverage_ratio.no_exposure",
        output_path="intermediate_values.no_exposure",
        meaning="Whether player has zero landing exposure",
        calculation_type="coverage_ratio",
        scenario_function="zeroThreatRiskInput",
        scenario_json="risk_coverage/zero_threat.json",
        test_module="test_coverage_ratio_fields",
        test_name="test_coverage_ratio_no_exposure",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="dangerous_monopoly_availability.dangerous_predicate",
        output_path="intermediate_values.dangerous_predicate",
        meaning="Dangerous monopoly availability predicate result",
        calculation_type="dangerous_monopoly_availability",
        scenario_function="exactlyThreeHousesEachInput",
        scenario_json="development_capability/exactly_three_houses_each.json",
        test_module="test_dangerous_monopoly_availability_fields",
        test_name="test_dangerous_monopoly_availability_dangerous_predicate",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="development_capability.predicate",
        output_path="intermediate_values.predicate",
        meaning="Development capability predicate name",
        calculation_type="development_capability",
        scenario_function="exactlyThreeHousesEachInput",
        scenario_json="development_capability/exactly_three_houses_each.json",
        test_module="test_development_capability_fields",
        test_name="test_development_capability_predicate",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="final_conclusions",
        output_path="final_conclusions",
        meaning="Final deterministic conclusions object",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_final_conclusions",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="id",
        output_path="id",
        meaning="Unique stable identifier for the evidence object",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_id",
        expected_invariant="evidence_static_trade_imbalance_001",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.available_risk_resources",
        output_path="intermediate_values.available_risk_resources",
        meaning="Available risk resources",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_available_risk_resources",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.bounded_risk_penalty",
        output_path="intermediate_values.bounded_risk_penalty",
        meaning="Final bounded penalty",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_bounded_risk_penalty",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.coverage_ratio",
        output_path="intermediate_values.coverage_ratio",
        meaning="Resources / Threat ratio",
        calculation_type="immediate_risk",
        scenario_function="zeroThreatRiskInput",
        scenario_json="risk_coverage/zero_threat.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_coverage_ratio",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.coverage_ratio_component",
        output_path="intermediate_values.coverage_ratio_component",
        meaning="Risk component from ratio",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_coverage_ratio_component",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.coverage_ratio_tier",
        output_path="intermediate_values.coverage_ratio_tier",
        meaning="Coverage ratio tier",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_coverage_ratio_tier",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.largest_threat",
        output_path="intermediate_values.largest_threat",
        meaning="Largest single-landing threat",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_largest_threat",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.maximum_risk_penalty",
        output_path="intermediate_values.maximum_risk_penalty",
        meaning="Maximum allowed penalty",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_maximum_risk_penalty",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.minimum_risk_penalty",
        output_path="intermediate_values.minimum_risk_penalty",
        meaning="Minimum allowed penalty",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_minimum_risk_penalty",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.risk_label",
        output_path="intermediate_values.risk_label",
        meaning="Risk severity label",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_risk_label",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.risk_margin",
        output_path="intermediate_values.risk_margin",
        meaning="Resources minus threat",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_risk_margin",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.surplus_or_deficit_amount",
        output_path="intermediate_values.surplus_or_deficit_amount",
        meaning="Surplus or deficit amount",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_surplus_or_deficit_amount",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.surplus_or_deficit_component",
        output_path="intermediate_values.surplus_or_deficit_component",
        meaning="Risk component from surplus/deficit",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_surplus_or_deficit_component",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.surplus_or_deficit_tier",
        output_path="intermediate_values.surplus_or_deficit_tier",
        meaning="Surplus/deficit tier",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_surplus_or_deficit_tier",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.uncapped_risk_penalty",
        output_path="intermediate_values.uncapped_risk_penalty",
        meaning="Uncapped risk penalty",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_uncapped_risk_penalty",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="immediate_risk.warnings",
        output_path="intermediate_values.warnings",
        meaning="Risk warnings generated",
        calculation_type="immediate_risk",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_immediate_risk_fields",
        test_name="test_immediate_risk_warnings",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="intermediate_calculations",
        output_path="intermediate_calculations",
        meaning="Array of Intermediate Calculation Items",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_intermediate_calculations",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.calculation_type",
        output_path="intermediate_calculations[*].calculation_type",
        meaning="Canonical calculation type from the registry",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_calculation_type",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.dependent_calculation_ids",
        output_path="intermediate_calculations[*].dependent_calculation_ids",
        meaning="IDs of calculations consuming this result",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_dependent_calculation_ids",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.description",
        output_path="intermediate_calculations[*].description",
        meaning="Human-readable calculation description",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_description",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.formula",
        output_path="intermediate_calculations[*].formula",
        meaning="Mathematical formula (when formula-based)",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_formula",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.id",
        output_path="intermediate_calculations[*].id",
        meaning="Unique stable calculation identifier",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_id",
        expected_invariant="calc_001",
    ),
    OutputFieldCoverageEntry(
        field_key="item.input_references",
        output_path="intermediate_calculations[*].input_references",
        meaning="Machine-readable input object references",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_input_references",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.input_values",
        output_path="intermediate_calculations[*].input_values",
        meaning="Factual values read from input",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_input_values",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.intermediate_values",
        output_path="intermediate_calculations[*].intermediate_values",
        meaning="Intermediate values for result reproduction",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_intermediate_values",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.limitations",
        output_path="intermediate_calculations[*].limitations",
        meaning="Known limitations affecting interpretation",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_limitations",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.metadata",
        output_path="intermediate_calculations[*].metadata",
        meaning="Optional implementation-specific metadata",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_metadata",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.missing_inputs",
        output_path="intermediate_calculations[*].missing_inputs",
        meaning="Required inputs that were unavailable",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_missing_inputs",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.procedure",
        output_path="intermediate_calculations[*].procedure",
        meaning="Deterministic procedure description",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_procedure",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.result",
        output_path="intermediate_calculations[*].result",
        meaning="Calculation result",
        calculation_type="-",
        scenario_function="propertyWithHotelTransferInput",
        scenario_json="base_asset_value/property_with_hotel_transfer.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_result",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.side",
        output_path="intermediate_calculations[*].side",
        meaning="Board state side",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_side",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.side.after",
        output_path="intermediate_calculations[*].side",
        meaning="After side coverage",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_side_after",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.side.before",
        output_path="intermediate_calculations[*].side",
        meaning="Before side coverage",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_side_before",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.side.delta",
        output_path="intermediate_calculations[*].side",
        meaning="Delta side coverage",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_side_delta",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.side.trade",
        output_path="intermediate_calculations[*].side",
        meaning="Trade side coverage",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_side_trade",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.sources",
        output_path="intermediate_calculations[*].sources",
        meaning="Provenance of configurable/default values",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_sources",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.status",
        output_path="intermediate_calculations[*].status",
        meaning="Calculation completion status",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_status",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.status.COMPLETE",
        output_path="intermediate_calculations[*].status",
        meaning="COMPLETE status coverage",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_status_COMPLETE",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.status.ERROR",
        output_path="intermediate_calculations[*].status",
        meaning="ERROR status coverage",
        calculation_type="-",
        scenario_function="multiPartyTradeInput",
        scenario_json="invalid_input/multi_party_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_status_ERROR",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.status.UNAVAILABLE",
        output_path="intermediate_calculations[*].status",
        meaning="UNAVAILABLE status coverage",
        calculation_type="-",
        scenario_function="unavailableMonopolyRentInput",
        scenario_json="custom_board/unavailable_monopoly_rent.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_status_UNAVAILABLE",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.status.PARTIAL",
        output_path="intermediate_calculations[*].status",
        meaning="PARTIAL status coverage",
        calculation_type="-",
        scenario_function="partialMonopolyRentInput",
        scenario_json="custom_board/partial_monopoly_rent.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_status_PARTIAL",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="item.subject",
        output_path="intermediate_calculations[*].subject",
        meaning="Entity identifiers involved in calculation",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_subject",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="item.unit",
        output_path="intermediate_calculations[*].unit",
        meaning="Result unit or semantic type",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_item_unit",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="landing_exposure.threat_property_id",
        output_path="intermediate_values.threat_property_id",
        meaning="Property ID of the landing threat",
        calculation_type="landing_exposure",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_landing_exposure_fields",
        test_name="test_landing_exposure_threat_property_id",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="largest_threat.landing_exposure",
        output_path="intermediate_values.landing_exposure",
        meaning="Landing exposure component of largest threat",
        calculation_type="largest_threat",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_largest_threat_fields",
        test_name="test_largest_threat_landing_exposure",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="metadata",
        output_path="metadata",
        meaning="Evidence-level metadata",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_metadata",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="metadata.implementation_overrides",
        output_path="metadata.implementation_overrides",
        meaning="Implementation overrides to specification defaults",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_metadata_fields",
        test_name="test_metadata_implementation_overrides",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="metadata.specification_dependencies",
        output_path="metadata.specification_dependencies",
        meaning="Specification dependencies (e.g., Risk Reference)",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_metadata_fields",
        test_name="test_metadata_specification_dependencies",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="metadata.specification_dependencies.specification_id",
        output_path="metadata.specification_dependencies[*].specification_id",
        meaning="Dependency specification identifier",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_metadata_fields",
        test_name="test_metadata_specification_dependencies_specification_id",
        expected_invariant="monopoly_risk_reference",
    ),
    OutputFieldCoverageEntry(
        field_key="metadata.specification_dependencies.specification_version",
        output_path="metadata.specification_dependencies[*].specification_version",
        meaning="Dependency specification version",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_metadata_fields",
        test_name="test_metadata_specification_dependencies_specification_version",
        expected_invariant="1.0",
    ),
    OutputFieldCoverageEntry(
        field_key="monopoly_value.completed_groups",
        output_path="intermediate_values.completed_groups",
        meaning="List of completed group IDs",
        calculation_type="monopoly_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_monopoly_value_fields",
        test_name="test_monopoly_value_completed_groups",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="monopoly_value.per_group_values",
        output_path="intermediate_values.per_group_values",
        meaning="Per-group monopoly value details",
        calculation_type="monopoly_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_monopoly_value_fields",
        test_name="test_monopoly_value_per_group_values",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="monopoly_value.total_monopoly_value",
        output_path="intermediate_values.total_monopoly_value",
        meaning="Sum of all group monopoly values",
        calculation_type="monopoly_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_monopoly_value_fields",
        test_name="test_monopoly_value_total_monopoly_value",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="mortgage_capacity.result",
        output_path="intermediate_calculations[*].result",
        meaning="Mortgage capacity result value",
        calculation_type="mortgage_capacity",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_mortgage_capacity_fields",
        test_name="test_mortgage_capacity_result",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="purpose",
        output_path="purpose",
        meaning="Canonical purpose string",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_purpose",
        expected_invariant="trade ratio calculation and competitive advantage calculation",
    ),
    OutputFieldCoverageEntry(
        field_key="railroad_value.context_multiplier",
        output_path="intermediate_values.context_multiplier",
        meaning="Context multiplier applied to railroad value",
        calculation_type="railroad_value",
        scenario_function="fourRailroadsInput",
        scenario_json="railroad_value/four_railroads.json",
        test_module="test_railroad_value_fields",
        test_name="test_railroad_value_context_multiplier",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="railroad_value.railroad_count",
        output_path="intermediate_values.railroad_count",
        meaning="Count of railroads owned",
        calculation_type="railroad_value",
        scenario_function="fourRailroadsInput",
        scenario_json="railroad_value/four_railroads.json",
        test_module="test_railroad_value_fields",
        test_name="test_railroad_value_railroad_count",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="repair_exposure.repair_card_scenario",
        output_path="intermediate_values.repair_card_scenario",
        meaning="Repair card scenario identifier",
        calculation_type="repair_exposure",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_repair_exposure_fields",
        test_name="test_repair_exposure_repair_card_scenario",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="risk_margin.surplus_amount",
        output_path="intermediate_values.surplus_amount",
        meaning="Surplus amount in risk margin calculation",
        calculation_type="risk_margin",
        scenario_function="survivalRiskCriticalInput",
        scenario_json="risk_coverage/survival_risk_critical.json",
        test_module="test_risk_margin_fields",
        test_name="test_risk_margin_surplus_amount",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="sources",
        output_path="intermediate_calculations[*].sources",
        meaning="Source label coverage across calculations",
        calculation_type="-",
        scenario_function="customStreetGroupTradeInput",
        scenario_json="custom_board/custom_street_group.json",
        test_module="test_calculation_item_common_fields",
        test_name="test_sources",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="statistics",
        output_path="statistics",
        meaning="Calculation statistics",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_evidence_envelope_fields",
        test_name="test_statistics",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="statistics.calculation_count",
        output_path="statistics.calculation_count",
        meaning="Total number of calculations produced",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_statistics_fields",
        test_name="test_statistics_calculation_count",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_opportunity_score.criteria",
        output_path="intermediate_values.criteria",
        meaning="Strategic opportunity score criteria flags",
        calculation_type="strategic_opportunity_score",
        scenario_function="strategicBlockingTradeInput",
        scenario_json="blocking_value/strategic_blocking_trade.json",
        test_module="test_strategic_opportunity_fields",
        test_name="test_strategic_opportunity_score_criteria",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.base_asset_value",
        output_path="intermediate_values.base_asset_value",
        meaning="Base asset value component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_base_asset_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.blocking_value",
        output_path="intermediate_values.blocking_value",
        meaning="Blocking value component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_blocking_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.floor_applied",
        output_path="intermediate_values.floor_applied",
        meaning="Whether minimum floor was applied",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_floor_applied",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.house_control_bonus",
        output_path="intermediate_values.house_control_bonus",
        meaning="House control bonus component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_house_control_bonus",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.house_denial_bonus",
        output_path="intermediate_values.house_denial_bonus",
        meaning="House denial bonus component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_house_denial_bonus",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.immediate_risk_change",
        output_path="intermediate_values.immediate_risk_change",
        meaning="Immediate risk change (subtracted)",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_immediate_risk_change",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.monopoly_value",
        output_path="intermediate_values.monopoly_value",
        meaning="Monopoly value component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_monopoly_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.railroad_value",
        output_path="intermediate_values.railroad_value",
        meaning="Railroad value component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_railroad_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="strategic_value.strategic_opportunity_value",
        output_path="intermediate_values.strategic_opportunity_value",
        meaning="Strategic opportunity value component",
        calculation_type="strategic_value",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_strategic_value_fields",
        test_name="test_strategic_value_strategic_opportunity_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="subject.group_ids",
        output_path="intermediate_calculations[*].subject.group_ids",
        meaning="Group identifiers involved",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_subject_fields",
        test_name="test_subject_group_ids",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="subject.player_ids",
        output_path="intermediate_calculations[*].subject.player_ids",
        meaning="Player identifiers involved",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_subject_fields",
        test_name="test_subject_player_ids",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="subject.property_ids",
        output_path="intermediate_calculations[*].subject.property_ids",
        meaning="Property identifiers involved",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_subject_fields",
        test_name="test_subject_property_ids",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="subject.trade_id",
        output_path="intermediate_calculations[*].subject.trade_id",
        meaning="Trade identifier",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_subject_fields",
        test_name="test_subject_trade_id",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="subject.transfer_ids",
        output_path="intermediate_calculations[*].subject.transfer_ids",
        meaning="Transfer identifiers involved",
        calculation_type="-",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_subject_fields",
        test_name="test_subject_transfer_ids",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.division_denominator",
        output_path="intermediate_values.division_denominator",
        meaning="Denominator for ratio (max(1, lowest))",
        calculation_type="trade_ratio",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_division_denominator",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.highest_strategic_value",
        output_path="intermediate_values.highest_strategic_value",
        meaning="Higher of the two strategic values",
        calculation_type="trade_ratio",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_highest_strategic_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.lowest_strategic_value",
        output_path="intermediate_values.lowest_strategic_value",
        meaning="Lower of the two strategic values",
        calculation_type="trade_ratio",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_lowest_strategic_value",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.maximum_trade_ratio",
        output_path="intermediate_values.maximum_trade_ratio",
        meaning="Maximum allowed ratio (cap)",
        calculation_type="trade_ratio",
        scenario_function="balancedTradeInput",
        scenario_json="trade_ratio/balanced_trade.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_maximum_trade_ratio",
        expected_invariant="see handler assertion",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.published_trade_ratio",
        output_path="intermediate_values.published_trade_ratio",
        meaning="Final capped ratio",
        calculation_type="trade_ratio",
        scenario_function="ratioGreaterThanFiveInput",
        scenario_json="trade_ratio/ratio_greater_than_five.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_published_trade_ratio",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
    OutputFieldCoverageEntry(
        field_key="trade_ratio.raw_trade_ratio",
        output_path="intermediate_values.raw_trade_ratio",
        meaning="Uncapped raw ratio",
        calculation_type="trade_ratio",
        scenario_function="ratioGreaterThanFiveInput",
        scenario_json="trade_ratio/ratio_greater_than_five.json",
        test_module="test_trade_ratio_fields",
        test_name="test_trade_ratio_raw_trade_ratio",
        expected_invariant="see handler assertion",
        assertion_tier="SEMANTIC",
    ),
)


def get_coverage_by_field() -> dict[str, OutputFieldCoverageEntry]:
    """Return coverage entries keyed by field_key."""
    return {entry.field_key: entry for entry in OUTPUT_FIELD_COVERAGE}


def get_coverage_by_module(test_module: str) -> tuple[OutputFieldCoverageEntry, ...]:
    """Return coverage entries for a test module."""
    return tuple(e for e in OUTPUT_FIELD_COVERAGE if e.test_module == test_module)


def get_required_scenarios() -> frozenset[str]:
    """Return scenario functions referenced by field coverage."""
    return frozenset(e.scenario_function for e in OUTPUT_FIELD_COVERAGE if not e.waived)
