from Monopoly.Shared.Domain.StrEnumCompat import StrEnum


class ValueSourceLabel(StrEnum):
    IMPLEMENTATION_OVERRIDE = "IMPLEMENTATION_OVERRIDE"
    GAME_CONFIGURATION = "GAME_CONFIGURATION"
    GAME_CONFIGURATION_OVERRIDE = "GAME_CONFIGURATION_OVERRIDE"
    BOARD_STATE = "BOARD_STATE"
    BOARD_STATE_RENT_TABLE = "BOARD_STATE_RENT_TABLE"
    RISK_REFERENCE = "RISK_REFERENCE"
    RISK_REFERENCE_DEFAULT = "RISK_REFERENCE_DEFAULT"
    CLASSIC_DEFAULT = "CLASSIC_DEFAULT"
    NEUTRAL_CUSTOM_GROUP_DEFAULT = "NEUTRAL_CUSTOM_GROUP_DEFAULT"
    SPECIFICATION_DEFAULT = "SPECIFICATION_DEFAULT"
    UNAVAILABLE = "UNAVAILABLE"
