"""Specification document repository port."""

from __future__ import annotations

from typing import Protocol


class SpecificationRepository(Protocol):
    def readFile(self, relativePath: str) -> bytes: ...

    def verifySpecificationIdentity(self, specificationId: str, requiredVersion: str) -> bool: ...

    def discoverDeliverablePaths(self, relativeDirectory: str) -> tuple[str, ...]: ...

    def llmEvaluatorBundlePaths(self) -> tuple[str, ...]: ...

    def staticEvaluatorBundlePaths(self) -> tuple[str, ...]: ...

    def defaultJudgeBundlePaths(self) -> tuple[str, ...]: ...

    def fallbackBundlePaths(self) -> tuple[str, ...]: ...

    def minimalBundlePaths(self) -> tuple[str, ...]: ...
